### ISSUE TITLE
qtutils issue?

### ISSUE THREAD

**Issue by andyyuan78** [val-iisc/expresso#2]
ubgpu@ubgpu:~/github/expresso$ sh run_expresso.sh
Traceback (most recent call last):
  File "/home/ubgpu/github/expresso/src/main/main.py", line 13, in <module>
    from qtutils import inmain_later,inthread,inmain
ImportError: No module named qtutils
ubgpu@ubgpu:~/github/expresso$ 

ubgpu@ubgpu:~/github/expresso$ sudo -H pip install qtutils
Requirement already satisfied (use --upgrade to upgrade): qtutils in /usr/local/lib/python2.7/dist-packages
ubgpu@ubgpu:~/github/expresso$

**Comment by crazymuse** [comment]
Are you using ubuntu 14.04? Because this error comes only in 12.04. If so, i will soon let you know the fix for 12.04 . . .

**Comment by ravika** [comment]
qtutils ought to have been installed when you ran the [install script](https://github.com/val-iisc/expresso/blob/master/install.sh) . In particular, the following line would have gotten executed : `sudo pip install --proxy $HTTP_PROXY qtutils` (if you set a proxy) or `sudo pip install qtutils`

Try the pip install separately on a command line and see if that does the trick.

**Comment by andyyuan78** [comment]
ubgpu@ubgpu:~$ sudo -H pip install qtutils
Collecting qtutils
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading qtutils-1.6.0.tar.gz (8.2MB)
    100% |████████████████████████████████| 8.2MB 80kB/s 
Building wheels for collected packages: qtutils
  Running setup.py bdist_wheel for qtutils
  Stored in directory: /root/.cache/pip/wheels/83/15/ed/edad1a511003f0a4bdaed358104d3724812f3ebc3063ac3546
Successfully built qtutils
Installing collected packages: qtutils
Successfully installed qtutils-1.6.0
ubgpu@ubgpu:~$ cd github/expresso/
ubgpu@ubgpu:~/github/expresso$ 
ubgpu@ubgpu:~/github/expresso$ sh run_expresso.sh
Traceback (most recent call last):
  File "/home/ubgpu/github/expresso/src/main/main.py", line 13, in <module>
    from qtutils import inmain_later,inthread,inmain
ImportError: No module named qtutils
ubgpu@ubgpu:~/github/expresso$

**Comment by crazymuse** [comment]
which version of Ubuntu are you using? 12.04 or 14.04?

**Comment by andyyuan78** [comment]
14.04

**Comment by crazymuse** [comment]
This error is not being replicated on fresh 14.04 system, still you can try as given bellow
sudo su <username>
pip install qtutils
exit
Sometimes, I have observed that python puts installed packages at a different location(in some versions) when sudo is used. Although I am not very sure about it. If nothing works, try appending path externally to PYTHONPATH variable, or do sys.path.append(<path to externally compiled qtutils library>), or you may try playing with PATH variable and ldconfig. Try out these hooks and see if they work.

**Comment by andyyuan78** [comment]
fixed by run
sudo apt-get remove python-qt4

**Comment by talatshaikh29** [comment]
@andyyuan78 You must have Anaconda installed. Go to ~/.bash_profile & change PYTHON_PATH variable to add /usr/local/lib/python2.7/dist-packages. Maybe that will help
