### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation  in ubuntu14.04

### ISSUE THREAD

**Issue by andyyuan78** [val-iisc/expresso#6]
ubgpu@ubgpu:~/source_for_caffe/1/expresso/tutorials/data$ vim preprocess_cifar_10.py 
ubgpu@ubgpu:~/source_for_caffe/1/expresso/tutorials/data$ python preprocess_cifar_10.py 
  File "preprocess_cifar_10.py", line 20
    dset=f.create_dataset('data',(50000,3,32,32),dtype='float')
                                                              ^
TabError: inconsistent use of tabs and spaces in indentation
ubgpu@ubgpu:~/source_for_caffe/1/expresso/tutorials/data$ vim preprocess_cifar_10.py 
ubgpu@ubgpu:~/source_for_caffe/1/expresso/tutorials/data$ python preprocess_cifar_10.py 
  File "preprocess_cifar_10.py", line 24
    dset[30000:40000]=np.reshape(np.array(unpickle('cifar-10-batches-py/data_batch_4')['data']),[10000,3,32,32])
                                                                                                               ^
TabError: inconsistent use of tabs and spaces in indentation

of course, I knew how to fix it; but it is a boring job

**Comment by crazymuse** [comment]
I am not sure, why u got this error, because we had tested the same in different machines, however I will try to look into tab settings.
